alias aer="source $HOME/.bash_aliases"
alias reload="source $HOME/.bashrc"
alias ae="vim $HOME/.bash_aliases; aer;"
alias vimrc='vim $HOME/.vimrc'
alias bashrc='vim $HOME/.bashrc; reload'
alias fzfrc='vim $HOME/.fzf.bash'
alias cross_gcc=i686-elf-gcc
alias ycm_generate=$HOME/.vim/bundle/YCM-Generator/config_gen.py
alias ycm_tern_gen='cp $WORKSPACE/vimrc/.tern-project $PWD'
alias pcalc=$HOME/bin/pcalc.py
alias clion=$HOME/clion/clion-2018.1/bin/clion.sh
alias cs="xclip -selection clipboard"
alias vs="xclip -o -selection clipboard"
alias c="xclip"
alias v="xclip -o"
#alias pip=/usr/bin/pip2
alias p="python3"
alias p2=python2
alias p3=python3
alias ipy3=ipython3
alias ipy=ipython3
alias psi="python setup.py install"
alias psc="python setup.py clean"
alias pydebug='pudb'
alias convert_ipy_notebook="jupyter nbconvert --to script"
alias linecount=loc
alias objd='objdump -Mintel -D'
alias ls="ls -X --color=auto"
alias l="ls -XFlha"
alias grep='grep --color'
alias g=grep.py $argv
alias vim_background_color="$HOME/bin/vim_background_color.py"
alias vimrc_min="cat $WORKSPACE/vimrc/vimrc_minimal | cs"
alias vim_hex="cat $WORKSPACE/vimrc/vim_hex | cs"
#alias vim="PYTHONPATH=$PYTHONPATH:/usr/lib/python3.6/site-packages/ vim"
#alias v="PYTHONPATH=$PYTHONPATH:/usr/lib/python3.6/site-packages/ vim"
#alias vim="PYTHONPATH=$PYTHONPATH:$HOME/anaconda3/lib/python3.7/site-packages/ vim"
#alias v="PYTHONPATH=$PYTHONPATH:$HOME/anaconda3/lib/python3.7/site-packages/ vim"
alias v=vim
alias scheme_vim="MYVIMRC=~/.scheme_vimrc vim"
alias git_developers='git shortlog -sne'
alias gcl='git clone'
alias gpu='git push'
alias gs="git status"
alias gl="git log"
alias gb="git branch"
alias ga="git add"
alias gc="git checkout"
alias git_discard="git checkout --"
alias git_unstage="git reset HEAD"
alias gco="git commit"
alias gd="git diff"
alias git_submodule_recursive="git submodule update --init --recursive"
alias git_submodule_sync='git submodule sync'
alias git_log_pretty="git log --graph --decorate --pretty=oneline --abbrev-commit"
alias gg="git grep -n --color"
alias gdb_vanilla="gdb --command $WORKSPACE/vimrc/gdb_scripts/gdbvanilla --args"
alias gdb_peda="gdb --command $WORKSPACE/vimrc/gdb_scripts/peda.gdb --args"
alias gdb_pwndbg="gdb --command $WORKSPACE/vimrc/gdb_scripts/pwndbg.gdb --args"
alias cdsoftmmu="cd $PWNABLE/HackersSecret/softmmu"
alias cdpwn="cd $WARGAMES/pwnable_kr"
alias cdwar="cd $WARGAMES"
alias wargame_environ_setup="cat $WARGAMES/scripts/env.sh | cs"
alias shellcode_generate="$WARGAMES/shellcode/shellcode.py"
alias cdnar="cd $WARGAMES/narnia"
alias cdbehemoth="cd $WARGAMES/behemoth"
alias cdvortex="cd $WARGAMES/vortex"
alias cdnatas="cd $WARGAMES/natas"
alias cdvimrc="cd $WORKSPACE/vimrc"
alias cdblog="cd $WORKSPACE/bodgergely.github.io"
alias cdhacking="cd $HACKING"
alias cdworkspace="cd $HOME/workspace/"
alias cdmyrepos='cd $WORKSPACE/my_repos'
alias cdbodos="cd $WORKSPACE/bodos/src"
alias cdlazyprogrammer="cd $HOME/workspace/AI/lazyprogrammer/machine_learning_examples"
alias cdsitepackages="cd /usr/lib/python3.6/site-packages"
alias cdstats="cd $WORKSPACE/stats"
alias cdbayes="cd $WORKSPACE/stats/ThinkBayes"
alias cdhandson_ml="cd $HANDSON_ML_PATH"
alias cdplayground="cd $WORKSPACE/playground"
alias cdgym="cd $WORKSPACE/AI/openai/gym"
alias cdtlpi="cd $WORKSPACE/sysprog/tlpi"
alias cdbooks="cd $HOME/Dropbox/books"
alias cdlinux="cd $WORKSPACE/linux"
alias cdkernelhacking="cd $HACKING/kernel_hacking"
alias cdbusybox="cd $HOME/busybox/build"
alias cdnand2tetris="cd $WORKSPACE/coursera/nand2tetris"
alias cdembedded="cd $WORKSPACE/coursera/embedded_boulder/ese-coursera-course1"
alias cdweb="cd $WORKSPACE/my_repos/website"
alias cdhtb='cd $WARGAMES/pentestlabs/hackthebox'
alias cdbhp='cd $WORKSPACE/my_repos/black_hat_python/BHP-Code'
alias cdrust='cd $WARGAMES/tutorials/lang-tut/rust'
alias cddropbox='cd $HOME/Dropbox'
alias cdlangtut='cd $HOME/tutorials/lang-tut/'
alias cdtmp='cd /tmp'
alias cdudemy='cd $WORKSPACE/my_repos/udemy'
alias cdgo='cd $HOME/workspace/go/src'
alias cdgo_playground='cd $GOPATH/src/playground'
alias cdutility_tools='cd $WORKSPACE/my_repos/utility_tools'
alias apache_restart="sudo systemctl restart apache2.service"
alias apache_status="sudo systemctl status apache2.service"
alias apache_start="sudo systemctl start apache2.service"
alias apache_stop="sudo systemctl stop apache2.service"
alias agi="sudo apt-get install"
alias agi_yes="sudo apt-get -y install"
alias agr="sudo apt-get remove"
alias cdmetasploit="cd /opt/metasploit-framework/embedded/framework"
alias diskspace_check='ncdu'
alias jekyll_serve="bundle exec jekyll serve"
alias configure_debug_build='./configure CFLAGS="-ggdb3 -O0" CXXFLAGS="-ggdb3 -O0" LDFLAGS="-ggdb3"'
alias configure_32='./configure CFLAGS="-m32 -O2" CXXFLAGS="-m32 -O2" LDFLAGS="-m32"'
alias torbrowser='~/tor/tor-browser_en-US/start-tor-browser.desktop'
#alias torbrowser='xhost si:localuser:geri;sudo -u geri -H torbrowser-launcher'
alias network_restart='sudo systemctl restart network-manager.service'
alias ping_google='ping www.google.com'
alias ports_open='sudo netstat -peanut'
alias ports_listening='sudo netstat -ltup'
alias Cutter='~/cutter/Cutter-v1.7.1-x86_64.AppImage'
alias webassembly_setup_env='source $WEBASSEMBLY/emsdk/emsdk_env.sh'
alias emrun_here='emrun --no_browser --port 8080 .'
#alias nmap_1='sudo nmap -v -A -sS -oX nmap_output'
alias nmap_syn='sudo nmap -v -A -sS'
alias nmap_top_ports_20='sudo nmap -v -sT --top-ports 20'
alias ssh_start='sudo service ssh start'
alias ssh_stop='sudo service ssh stop'
alias ssh_status='sudo service ssh status'
#alias sqlmap='python ~/bin/sqlmap.py'
alias ssh_raspberry_1='ssh pi@$RASPBERRY_1' 
alias mount_shared='~/Desktop/mount-shared-folders.sh'
alias cdshared='cd ~/operating_systems/linux/kali/shared'
alias conn_offsec_network='cd $OFFSEC_DIR/offsec_connectivity_pack; cat auth.txt | cs; ./connect.sh'
alias test_offsec_connection='ping 10.11.1.220'
alias win7_machine_connect='cd $OFFSEC_DIR/offsec_connectivity_pack; ./win7_remote_desktop.sh'
alias win7_machine_connect_fullscreen='cd $OFFSEC_DIR/offsec_connectivity_pack; ./win7_remote_desktop_fullscreen.sh'
alias cdlab='cd $LAB'
alias msfconsole='sudo msfconsole'
alias mingw_32_g++=i686-w64-mingw32-g++
alias mingw_64_g++=x86_64-w64-mingw32-g++
alias targz_compress='tar -czvf'
alias bzip_compress='tar -cjvf'
alias targz_uncompress='tar -xzvf'
alias bzip_uncompress='tar -xjvf'
alias cl='clear'
alias trace='sudo trace-cmd record -p function_graph'
alias eclipse='~/eclipse/eclipse/eclipse'
alias cl='clear'
alias php5_enable='sudo a2enmod php5.6'
alias php7_enable='sudo a2enmod php7.2'
alias php5_disable='sudo a2dismod php5.6'
alias php7_disable='sudo a2dismod php7.2'
alias vpn_connect_1=$HOME/vpn/vpn_sf.sh
alias vpn_connect_2=$HOME/vpn/vpn_lhr.sh
alias cdcf='cd $HOME/workspace/cf'
alias questions='vim $HOME/Dropbox/cloudflare/questions.md'
alias learn_nginx='vim $HOME/Dropbox/cloudflare/nginx.md'
alias learn_opentracing='vim $HOME/Dropbox/cloudflare/opentracing.md'
alias chrome-chat="google-chrome --app=https://chat.google.com/ --profile-directory='Profile 1'"
alias cdopenresty='cd $HOME/openresty_debug'
alias traceroute_icmp='sudo traceroute -I'
alias r=ranger
alias t='tree -FC'
alias k='kubectl'
alias perf_flame="perf_flame.sh &"
alias f='fzf | xargs vim'
alias parted_l='sudo parted -l'
alias fdisk_l='sudo fdisk -l'
alias mex='chmod +x'
alias cheatsheet='vim $WORKSPACE/vimrc/CHEATSHEET.md'
alias truecolor_test='curl -s https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh | bash'
